import 'package:TI.quest/pergunta.dart';

  final List<Pergunta> perguntas = [
    Pergunta(
      texto: 'Sobre a linguagem de programação Python, ela é?',
      respostas: ['Orientado a objetos', 'Baixo nível', 'Funcional', 'Obsoleta'],
      respostaCorreta: 'Orientada a objetos',
      peso: 2,
      imagemPergunta:'https://brandslogos.com/wp-content/uploads/images/large/python-logo.png',
    ),
    Pergunta(
      texto: 'O que é um banco de dados?',
      respostas: ['Uma coleção organizada de dados que pode ser facilmente acessados, gerenciada e atualizadas', 'É um sistema operacional', 'Um conjunto de computadores interligados que compartilham informações', 'Uma linguagem de programação orientada a objetos'],
      respostaCorreta: 'Uma coleção organizada de dados que pode ser facilmente acessados',
      peso: 3,
      imagemPergunta: 'http://pluspng.com/img-png/android-png-android-logo-png-1024.png'
    ),
Pergunta(
    texto: 'Qual linguagem de programação é usada para desenvolvimento de aplicativos Android?',
    respostas: ['Swift', 'Kotlin', 'Ruby', 'C#'],
    respostaCorreta: 'Kotlin',
  peso: 3,
  imagemPergunta: 'https://1000logos.net/wp-content/uploads/2020/09/Umbrella-Corporation-Logo-1536x960.png'
),
Pergunta(
  texto: 'O que é um firewall?',
    respostas: ['Um software antivírus', 'Uma rede de computadores', 'Um dispositivo de segurança de rede', 'Um sistema operacional'],
    respostaCorreta: 'Um dispositivo de segurança de rede',
  peso: 4,
    imagemPergunta: 'https://1000logos.net/wp-content/uploads/2020/09/Umbrella-Corporation-Logo-1536x960.png'
),
Pergunta(
 texto: 'O que é SQL usado para fazer?',
    respostas: ['Gerar relatórios', 'Desenvolver websites', 'Consultar e gerenciar bancos de dados', 'Criar gráficos'],
    respostaCorreta: 'Consultar e gerenciar bancos de dados',
  peso: 2,
    imagemPergunta: 'https://1000logos.net/wp-content/uploads/2020/09/Umbrella-Corporation-Logo-1536x960.png'
),
Pergunta(
  texto: 'O que significa a sigla "CPU"?',
    respostas: ['Central Processing Unit', 'Computer Personal Unit', 'Central Programming Unit', 'Computer Processing Unit'],
    respostaCorreta: 'Central Processing Unit',
  peso: 3,
    imagemPergunta: 'https://1000logos.net/wp-content/uploads/2020/09/Umbrella-Corporation-Logo-1536x960.png'
),
Pergunta(
    texto: 'Qual protocolo é usado para enviar e-mails?',
    respostas: ['HTTP', 'FTP', 'SMTP', 'IMAP'],
    respostaCorreta: 'SMTP',
  peso: 4,
    imagemPergunta: 'https://1000logos.net/wp-content/uploads/2020/09/Umbrella-Corporation-Logo-1536x960.png'
),
Pergunta(
  texto: 'Qual é a função principal do sistema operacional?',
    respostas: ['Gerenciar software e hardware do computador', 'Desenvolver aplicativos', 'Proteger contra vírus', 'Manter a segurança da rede'],
    respostaCorreta: 'Gerenciar software e hardware do computador',
  peso: 4,
    imagemPergunta: 'https://jornaldosertaope.com.br/wp-content/uploads/2020/09/Vista-panoramica-da-cidade-de-Arcoverde-Foto-Divulgacao-scaled.jpg'
),
Pergunta(
  texto: 'Qual linguagem é principalmente usada para desenvolvimento web front-end?',
    respostas: ['Java', 'C++', 'Python', 'JavaScript'],
    respostaCorreta: 'JavaScript',
  peso: 3,
    imagemPergunta: 'https://media.metrolatam.com/2019/11/18/lula-7bdd95d7832e5391412b7fd2f4f5ceca-1200x800.jpg'
),
Pergunta(
    texto: 'O que é um endereço IP?',
    respostas: ['Um endereço de Protocolo da Internet', 'Um tipo de memória de computador', 'Um software antivírus', 'Um dispositivo de rede'],
    respostaCorreta: 'Um endereço de Protocolo da Internet',
  peso: 3,
    imagemPergunta: 'https://media.metrolatam.com/2019/11/18/lula-7bdd95d7832e5391412b7fd2f4f5ceca-1200x800.jpg'
),
Pergunta(
   texto: 'Qual é a função do comando "ping"?',
    respostas: ['Verificar a conectividade de rede', 'Transferir arquivos', 'Configurar roteadores', 'Proteger contra malware'],
    respostaCorreta: 'Verificar a conectividade de rede',
  peso: 4,
    imagemPergunta: 'https://media.metrolatam.com/2019/11/18/lula-7bdd95d7832e5391412b7fd2f4f5ceca-1200x800.jpg'
),
Pergunta(
    texto: 'Qual é a diferença entre HTTP e HTTPS?',
    respostas: ['HTTPS usa criptografia para segurança, enquanto HTTP não', 'HTTP é mais rápido que HTTPS', 'HTTPS é usado apenas para e-mails', 'HTTP é um protocolo mais novo que HTTPS'],
    respostaCorreta: 'HTTPS usa criptografia para segurança, enquanto HTTP não',
  peso: 3,
    imagemPergunta: 'https://media.metrolatam.com/2019/11/18/lula-7bdd95d7832e5391412b7fd2f4f5ceca-1200x800.jpg'
),
Pergunta(
   texto: 'O que é um arquivo executável?',
    respostas: ['Um arquivo que contém um programa que pode ser executado pelo computador', 'Um tipo de arquivo de imagem', 'Um documento de texto', 'Um arquivo de áudio'],
    respostaCorreta: 'Um arquivo que contém um programa que pode ser executado pelo computador',
  peso: 2,
    imagemPergunta: 'https://media.metrolatam.com/2019/11/18/lula-7bdd95d7832e5391412b7fd2f4f5ceca-1200x800.jpg'
),
Pergunta(
  texto: 'Qual é a função de um roteador?',
    respostas: ['Direcionar pacotes de dados entre redes', 'Armazenar arquivos', 'Proteger contra vírus', 'Monitorar uso de CPU'],
    respostaCorreta: 'Direcionar pacotes de dados entre redes',
  peso: 2,
    imagemPergunta: 'https://media.metrolatam.com/2019/11/18/lula-7bdd95d7832e5391412b7fd2f4f5ceca-1200x800.jpg'
),
Pergunta(
   texto: 'O que é um malware?',
    respostas: ['Um software malicioso projetado para causar danos', 'Um tipo de firewall', 'Um programa de proteção de dados', 'Um dispositivo de rede'],
    respostaCorreta: 'Um software malicioso projetado para causar danos',
    peso: 3,
    imagemPergunta: 'https://media.metrolatam.com/2019/11/18/lula-7bdd95d7832e5391412b7fd2f4f5ceca-1200x800.jpg'
),
Pergunta(
   texto: 'O que é um backup de dados?',
    respostas: ['Uma cópia de dados armazenada para recuperação em caso de falha', 'Um programa de otimização de sistema', 'Um tipo de software de criptografia', 'Um dispositivo de rede'],
    respostaCorreta: 'Uma cópia de dados armazenada para recuperação em caso de falha',
    peso: 3,
    imagemPergunta: 'https://media.metrolatam.com/2019/11/18/lula-7bdd95d7832e5391412b7fd2f4f5ceca-1200x800.jpg'
),
Pergunta(
    texto: 'O que é o DevOps?',
    respostas: ['Uma prática que integra desenvolvimento de software e operações de TI', 'Um tipo de software de gerenciamento de projetos', 'Uma técnica de programação', 'Um protocolo de rede'],
    respostaCorreta: 'Uma prática que integra desenvolvimento de software e operações de TI',
    peso:3,
    imagemPergunta: 'https://media.metrolatam.com/2019/11/18/lula-7bdd95d7832e5391412b7fd2f4f5ceca-1200x800.jpg'
),
Pergunta(
    texto: 'O que é um algoritmo?',
    respostas: ['Uma sequência de instruções para resolver um problema', 'Um tipo de software de rede', 'Uma linguagem de programação', 'Um componente de hardware'],
    respostaCorreta: 'Uma sequência de instruções para resolver um problema',
    peso:4,
    imagemPergunta: 'https://media.metrolatam.com/2019/11/18/lula-7bdd95d7832e5391412b7fd2f4f5ceca-1200x800.jpg'
),
Pergunta(
    texto: 'O que é um cookie no contexto da internet?',
    respostas: ['Um pequeno arquivo de dados armazenado no navegador do usuário', 'Um tipo de vírus de computador', 'Uma ferramenta de desenvolvimento web', 'Um protocolo de comunicação'],
    respostaCorreta: 'Um pequeno arquivo de dados armazenado no navegador do usuário',
    peso:3,
    imagemPergunta: 'https://media.metrolatam.com/2019/11/18/lula-7bdd95d7832e5391412b7fd2f4f5ceca-1200x800.jpg'
  ),
  Pergunta(
    texto: 'O que é uma API?',
    respostas: ['Um conjunto de regras que permite que softwares diferentes interajam', 'Um tipo de banco de dados', 'Uma linguagem de programação', 'Um protocolo de rede'],
    respostaCorreta: 'Um conjunto de regras que permite que softwares diferentes interajam',
    peso:4,
    imagemPergunta: 'https://media.metrolatam.com/2019/11/18/lula-7bdd95d7832e5391412b7fd2f4f5ceca-1200x800.jpg'
  ),
  Pergunta(
    texto: 'O que é a Internet das Coisas (IoT)?',
    respostas: ['A interconexão de dispositivos através da internet, permitindo que eles se comuniquem', 'Um tipo de banco de dados', 'Um protocolo de rede', 'Um software de segurança'],
    respostaCorreta: 'A interconexão de dispositivos através da internet, permitindo que eles se comuniquem',
    peso:4,
    imagemPergunta: 'https://media.metrolatam.com/2019/11/18/lula-7bdd95d7832e5391412b7fd2f4f5ceca-1200x800.jpg'
  ),
  Pergunta(
    texto: 'O que é um ataque de phishing?',
    respostas: ['Uma tentativa de obter informações sensíveis disfarçando-se como uma entidade confiável', 'Um tipo de malware', 'Uma ferramenta de desenvolvimento', 'Um protocolo de rede'],
    respostaCorreta: 'Uma tentativa de obter informações sensíveis disfarçando-se como uma entidade confiável',
    peso:3,
    imagemPergunta: 'https://media.metrolatam.com/2019/11/18/lula-7bdd95d7832e5391412b7fd2f4f5ceca-1200x800.jpg'
  ),
  Pergunta(texto: 'O que é uma rede sem fio (wireless)?',
    respostas: ['Uma rede que usa ondas de rádio para transmitir dados', 'Uma rede que usa cabos de fibra ótica', 'Um tipo de dispositivo de armazenamento', 'Uma ferramenta de desenvolvimento'],
    respostaCorreta: 'Uma rede que usa ondas de rádio para transmitir dados',
     peso:3,
    imagemPergunta: 'https://media.metrolatam.com/2019/11/18/lula-7bdd95d7832e5391412b7fd2f4f5ceca-1200x800.jpg'),
Pergunta(
  texto: 'O que é a criptografia?',
    respostas: ['O processo de codificar informações para torná-las inacessíveis a usuários não autorizados', 'Um tipo de malware', 'Uma ferramenta de desenvolvimento', 'Um protocolo de rede'],
    respostaCorreta: 'O processo de codificar informações para torná-las inacessíveis a usuários não autorizados',
    peso:3,
    imagemPergunta: 'https://media.metrolatam.com/2019/11/18/lula-7bdd95d7832e5391412b7fd2f4f5ceca-1200x800.jpg'),
  Pergunta(
      texto: 'Qual das seguinte opções apresente um valor equivalete a 10 gigabytes?',
      respostas: ['10000 bytes', '100 megabytes', '0,01 terabytes', 'Nenhuma das anteriores'],
      respostaCorreta: '0,01 terabytes',
      peso: 1,
      imagemPergunta: 'https://www.electronics-tutorials.ws/wp-content/uploads/2022/08/binary-numbers.jpg',
    ),
    Pergunta(
      texto: 'Nome do teste feito para testar se um computador pensa da mesma forma que um ser humano',
      respostas: ['Turing', 'Alan', 'Capacidade', 'Individualidade'],
      respostaCorreta: 'Turing',
      peso: 2,
      imagemPergunta: 'https://www.electronics-tutorials.ws/wp-content/uploads/2022/08/binary-numbers.jpg',
    ),
    Pergunta(
      texto: 'Qual das seguinte opções apresente um valor equivalete a 3000000 bytes?',
      respostas: ['0,3 gigabytes', '3 megabytes', '300 kiloBytes', 'Nenhuma das anteriores'],
      respostaCorreta: '3 megabytes',
      peso: 1,
      imagemPergunta: 'https://www.electronics-tutorials.ws/wp-content/uploads/2022/08/binary-numbers.jpg',
    ),
    Pergunta(
      texto: 'Representa um indentificador exclusivo de um aparelho conectado a internet.',
      respostas: ['Root', 'Rota', 'Endereço', 'IP'],
      respostaCorreta: 'IP',
      peso: 1,
      imagemPergunta: 'https://upload.wikimedia.org/wikipedia/commons/thumb/4/45/Internet-icon.png/670px-Internet-icon.png',
    ),
    Pergunta(
      texto: 'Ao se utilizar o git para manuzear um projeto usuarios sao encorajados a adicionar um comentario junto com quaisquer mudanças para clarificação. Essa ação e conhecida como?',
      respostas: ['Comentario', 'Commit', 'Dev note', 'Changelog'],
      respostaCorreta: 'Commit',
      peso: 2,
      imagemPergunta: 'https://git-scm.com/images/logos/2color-lightbg@2x.png',
    ),
    Pergunta(
      texto: 'Dentre as opçoes a seguir, qual delas NÃO representa uma classificação de software educativo?',
      respostas: ['Simulador', 'Micromundos', 'Tutorial', 'Jogos Sérios'],
      respostaCorreta: 'Tutorial',
      peso: 3,
      imagemPergunta: 'https://upload.wikimedia.org/wikipedia/commons/thumb/7/78/Appleterminal2.png/800px-Appleterminal2.png',
    ),
    Pergunta(
      texto: 'Qual das opçoes a seguir NÃO representa um elemento do front-end?',
      respostas: ['Logica de negocio', 'Interação com usuario', 'Design grafico', 'Experiencia de usuario'],
      respostaCorreta: 'Logica de negocio',
      peso: 2,
      imagemPergunta: 'https://upload.wikimedia.org/wikipedia/commons/thumb/7/78/Appleterminal2.png/800px-Appleterminal2.png',
    ),
    Pergunta(
      texto: 'Qual das seguinte linguagens de programação NÃO e orientada a objetos?',
      respostas: ['Java', 'C', 'Pyton', 'C#'],
      respostaCorreta: 'C',
      peso: 4,
      imagemPergunta: 'https://upload.wikimedia.org/wikipedia/commons/thumb/7/78/Appleterminal2.png/800px-Appleterminal2.png',
    ),
    Pergunta(
      texto: 'Laços "elseif" apenas serão executados caso:',
      respostas: ['O if anterior estiver falso', 'A condição atual estiver correta', 'O elseif anteriror estiver falso', 'Todas as anteriores estiverem corretas'],
      respostaCorreta: 'Todas as anteriores estiverem corretas',
      peso: 4,
      imagemPergunta:'https://brandslogos.com/wp-content/uploads/images/large/python-logo.png',
    ),
    Pergunta(
      texto: 'Quem é o hardware responsável por interpretar os dados de entrada e transforma-los em dados de saída?',
      respostas: ['Placa mãe', 'Procesador', 'Memoria RAM', 'HD'],
      respostaCorreta: 'Processador',
      peso: 1,
      imagemPergunta: 'https://upload.wikimedia.org/wikipedia/commons/thumb/d/d5/Nvidia_gf4mx440_se.jpg/800px-Nvidia_gf4mx440_se.jpg',
    ),
    Pergunta(
      texto: 'Protocolo usado para envio de e-mail:',
      respostas: ['smtp', 'pop3', 'imap4', 'nenhuma das alternativas'],
      respostaCorreta: 'nenhuma das alternativas',
      peso: 2,
      imagemPergunta: 'https://cdn.pixabay.com/photo/2017/05/31/23/44/email-marketing-2362038_640.png',
    ),
    Pergunta(
      texto: 'Sabendo as proporções das unidades de medida, quantos bits constituem um byte?',
      respostas: ['8', '1024', '512', '128'],
      respostaCorreta: '8',
      peso: 1,
      imagemPergunta: 'https://www.electronics-tutorials.ws/wp-content/uploads/2022/08/binary-numbers.jpg',
    ),
    Pergunta(
      texto: 'O que é um kernel?',
      respostas: ['O usuário administrador do sistema', 'O núcleo do sistema operacional', 'O sistema operacional', 'Um comando do usuário root'],
      respostaCorreta: 'O núcleo do sistema operacional',
      peso: 2,
      imagemPergunta: 'https://upload.wikimedia.org/wikipedia/commons/thumb/7/78/Appleterminal2.png/800px-Appleterminal2.png',
    ),
    Pergunta(
      texto: 'O que é a distancia administrativa?',
      respostas: ['É a latencia que os protocolos de roteamento causam na rede.', 'É o tempo de delay do pacote até chegar no seu destino.', 'É o custo de cada salto do protocolo de roteamento.', 'É o custo de cada protocolo de roteamento.'],
      respostaCorreta: 'É o custo de cada protocolo de roteamento.',
      peso: 3,
      imagemPergunta: 'https://upload.wikimedia.org/wikipedia/commons/thumb/7/78/Appleterminal2.png/800px-Appleterminal2.png',
    ),
    Pergunta(
      texto: 'HTML é uma linguagem de',
      respostas: ['Estilização', 'Programação', 'Edição', 'Formatação'],
      respostaCorreta: 'Formatação',
      peso: 2,
      imagemPergunta: 'https://upload.wikimedia.org/wikipedia/commons/thumb/7/78/Appleterminal2.png/800px-Appleterminal2.png',
    ),
    Pergunta(
      texto: 'O que é um RAT?',
      respostas: ['Remote Anti Tools', 'Researcher Anti Tools', 'Remote Administration Tool', 'Refactor Assist Tool'],
      respostaCorreta: 'Remote Administration Tool',
      peso: 3,
      imagemPergunta: 'https://upload.wikimedia.org/wikipedia/commons/thumb/7/78/Appleterminal2.png/800px-Appleterminal2.png',
    ),
    Pergunta(
      texto: 'Qual destes malwares são usados para roubar dados da rede não criptografados?',
      respostas: ['Port Scanners', 'Sniffer', 'Bot', 'Keylogger'],
      respostaCorreta: 'Sniffer',
      peso: 2,
      imagemPergunta: 'https://upload.wikimedia.org/wikipedia/commons/thumb/7/78/Appleterminal2.png/800px-Appleterminal2.png',
    ),
    Pergunta(
      texto: 'Qual desses malwares não fazem mal ao computador?',
      respostas: ['Jokeware', 'Backdoor', 'Keylogger', 'Trojan'],
      respostaCorreta: 'Jokeware',
      peso: 1,
      imagemPergunta: 'https://upload.wikimedia.org/wikipedia/commons/thumb/7/78/Appleterminal2.png/800px-Appleterminal2.png',
    ),
    Pergunta(
      texto: 'Qual desse domínio foi criado para fornecer maior segurança?',
      respostas: ['http', 'hvp', 'https', 'www'],
      respostaCorreta: 'https',
      peso: 1,
      imagemPergunta: 'https://upload.wikimedia.org/wikipedia/commons/thumb/4/45/Internet-icon.png/670px-Internet-icon.png',
    ),
    Pergunta(
      texto: 'Sobre a linguagem de programação Python, ela é?',
      respostas: ['Orientado a objetos', 'Baixo nível', 'Funcional', 'Obsoleta'],
      respostaCorreta: 'Orientada a objetos',
      peso: 2,
      imagemPergunta:'https://brandslogos.com/wp-content/uploads/images/large/python-logo.png',
    ),
    Pergunta(
      texto: 'O que é um banco de dados?',
      respostas: ['Uma coleção organizada de dados que pode ser facilmente acessados, gerenciada e atualizadas', 'É um sistema operacional', 'Um conjunto de computadores interligados que compartilham informações', 'Uma linguagem de programação orientada a objetos'],
      respostaCorreta: 'Uma coleção organizada de dados que pode ser facilmente acessados',
      peso: 3,
      imagemPergunta: 'https://dhg1h5j42swfq.cloudfront.net/2023/05/09172211/database-g87972c042_1280-768x768.png'
    ),
    Pergunta(
      texto: 'Qual principio da localidade diz que se um item é referenciado, os items proximos tendem a ser referenciados em breve',
      respostas: ['Localidade Espacial', 'Localidade de Memória', 'Localidade Temporal', 'Localidade Proxima'],
      respostaCorreta: 'Localidade Espacial',
      peso: 2,
      imagemPergunta: 'https://upload.wikimedia.org/wikipedia/commons/thumb/d/d5/Nvidia_gf4mx440_se.jpg/800px-Nvidia_gf4mx440_se.jpg',
    ),
    Pergunta(
      texto: 'Nome de um software utilizado para captura de pacotes em redes de computadores:',
      respostas: ['Regedit', 'Nessus', 'Wireshark', 'Postman'],
      respostaCorreta: 'Wireshark',
      peso: 1,
      imagemPergunta: 'https://www.pngall.com/wp-content/uploads/4/Cyber-Security-PNG-Transparent-HD-Photo.png',
    ),
    Pergunta(
      texto: 'Qual o nome do tipo de sistema operacional nativo de aparelhos como DVD players, micro-ondas, etc?',
      respostas: ['Sistemas de nós sensores', 'Sistemas Multiusuário', 'Sistemas de Pequeno porte', 'Sistemas Embarcados'],
      respostaCorreta: 'Sistema Embarcados',
      peso: 2,
      imagemPergunta: 'https://upload.wikimedia.org/wikipedia/commons/thumb/7/78/Appleterminal2.png/800px-Appleterminal2.png',
    ),
    Pergunta(
      texto: 'Padrões de projeto são:',
      respostas: ['Abordagens prê-definidas e reutilizaveis para resolver problemas durante o desenvolvimento de software', 'Técnicas e processos para controle e monitoramento de desenvolvimento em equipe', 'Descrições de como são construida bibliotecas de software', 'Metodos e técnicas avançadas de orientação a objeto'],
      respostaCorreta: 'Abordagens prê-definidas e reutilizaveis para resolver problemas durante o desenvolvimento de software',
      peso: 4,
      imagemPergunta: 'https://digitalland.com.br/wp-content/uploads/2017/07/conheca-5-ferramentas-para-gestao-de-projetos-e-equipe-923x720.jpeg',
    ),
    Pergunta(
      texto: 'Um conjunto de diretrizes que definem formalmente as regras e os direitos dos usuários, visando sua proteção',
      respostas: ['Segurança da informação', 'Política de Segurança', 'Contrato de confiança', 'Nenhuma das alternativas'],
      respostaCorreta: 'Política de Segurança',
      peso: 2,
      imagemPergunta: 'https://jdimi.com/wp-content/uploads/sites/4/2022/03/Cyber-Security-PNG-Clipart-300x189.png',
    ),
    Pergunta(
      texto: 'Esse sistema e composto de processadores completos e de memoria compartilhada, controlado em software para evitar conflitos.',
      respostas: ['Multicomputador', 'Processador Vetorial', 'Processador Matricial', 'Multiprocessadores'],
      respostaCorreta: 'Multiprocessadores',
      peso: 1,
      imagemPergunta: 'https://upload.wikimedia.org/wikipedia/commons/thumb/d/d5/Nvidia_gf4mx440_se.jpg/800px-Nvidia_gf4mx440_se.jpg'
    ),
    Pergunta(
      texto: 'O modelo de qualidade de software que avalia os processos de desenvolvimento de software:',
      respostas: ['ISO 9001', 'ISO 12119', 'ISO 15504', 'ISO 25010'],
      respostaCorreta: 'ISO 15504',
      peso: 2,
      imagemPergunta: 'https://digitalland.com.br/wp-content/uploads/2017/07/conheca-5-ferramentas-para-gestao-de-projetos-e-equipe-923x720.jpeg',
    ),
    Pergunta(
      texto: 'Sobre o os principios SOLID e INCORRETOR afirmar que:',
      respostas: ['S representa o principio de Responsabilidade unica', 'O representa o principio de Aberto/Fechado', 'D representa o principio Dependencia Direta', 'I representa o principio da Segregação de Interface'],
      respostaCorreta: 'D representa o principio Dependencia Direta',
      peso: 3,
      imagemPergunta: 'https://digitalland.com.br/wp-content/uploads/2017/07/conheca-5-ferramentas-para-gestao-de-projetos-e-equipe-923x720.jpeg',
    ),
    Pergunta(
      texto: ' As opções a seguir são exemplos de compactadores de arquivos, EXCETO:',
      respostas: ['BandiZip', 'WinRAR', 'WinZip', 'Adobe Zip'],
      respostaCorreta: 'Adobe Zip',
      peso: 1,
      imagemPergunta: 'https://jdimi.com/wp-content/uploads/sites/4/2022/03/Cyber-Security-PNG-Clipart-300x189.png',
    ),
    Pergunta(
      texto: 'Qual das opções abaixo é uma ferramenta poderosa de extração de arquivos que pode abrir quase todos os formatos de arquivo comprimido mais populares?',
      respostas: ['Signal', 'WinRAR', 'Waze', 'Adobe Zip'],
      respostaCorreta: 'WinRAR',
      peso: 1,
      imagemPergunta: 'https://jdimi.com/wp-content/uploads/sites/4/2022/03/Cyber-Security-PNG-Clipart-300x189.png',
    ),
    Pergunta(
      texto: 'Tipo de software projetado para gerenciar recursos de hardware e fornecer serviços comuns para programas de aplicativos.',
      respostas: ['Software de sistema', 'Software de middleware', 'Software de middleware', 'Software de aplicativo'],
      respostaCorreta: 'Software de sistema',
      peso: 1,
      imagemPergunta: 'https://upload.wikimedia.org/wikipedia/commons/thumb/7/78/Appleterminal2.png/800px-Appleterminal2.png',
    ),
    Pergunta(
      texto: 'Tipo de software que pode ser executado, copiado, distribuído e modificado pelo usuário sem restrições.',
      respostas: ['Shareware', 'Commonware', 'Software livre', 'Software Proprietário'],
      respostaCorreta: 'Software livre',
      peso: 2,
      imagemPergunta: 'https://upload.wikimedia.org/wikipedia/commons/thumb/7/78/Appleterminal2.png/800px-Appleterminal2.png',
    ),
    Pergunta(
      texto: 'Qual é a principal característica de um software proprietário?',
      respostas: ['Obrigação de compartilhar modificações feitas no software com a comunidade.', 'Restrição do acesso ao código-fonte e à posse dos direitos autorais pelo desenvolvedor.', 'Disponibilidade gratuita para todos os usuários.', 'Ausência de bugs.'],
      respostaCorreta: 'Restrição do acesso ao código-fonte e à posse dos direitos autorais pelo desenvolvedor.', 
      peso: 2,
      imagemPergunta: 'https://upload.wikimedia.org/wikipedia/commons/thumb/7/78/Appleterminal2.png/800px-Appleterminal2.png',
    ),
    Pergunta(
      texto: 'O tipo de aprendizagem de máquina que se baseia em dados preparados para treinamento, quando se sabe o desfecho de cada registro do conjunto de dados, em geral previamente rotulados por um especialista, é a aprendizagem ',
      respostas: ['Aprendizagem Supervisionada', 'Aprendizagem independente', 'Aprendizagem Focada', 'Aprendizagem Assistida'],
      respostaCorreta: 'Aprendizagem Supervisionada',
      peso: 1,
      imagemPergunta: 'https://www.electronics-tutorials.ws/wp-content/uploads/2022/08/binary-numbers.jpg',
    ),
    Pergunta(
      texto: 'Qual das opçoes a seguir NÃO e uma caracteristica de um servidor proxy?',
      respostas: ['Monitor o acesso a rede', 'Fornece maior segurança', 'Equilibrar o trafico da rede', 'Alto custo por uso'],
      respostaCorreta: 'Alto custo por uso',
      peso: 3,
      imagemPergunta: 'https://upload.wikimedia.org/wikipedia/commons/thumb/4/45/Internet-icon.png/670px-Internet-icon.png',
    ),
    Pergunta(
      texto: 'Dentre os componentes de uma rede local de computadores (LAN),a Switch exerce a função de:',
      respostas: ['chavear logicamente as conexões da LAN para a trans- ferência dos pacotes de dados', 'gerenciar a rota dos pacotes por meio da verificação do tipo de dados.', ' monitorar os pacotes de dados provenientes da rede ampla (WAN) para a LAN, em busca de vírus.', 'monitorar os acessos provenientes da rede ampla (WAN) para a LAN, em busca de invasões.'],
      respostaCorreta: 'chavear logicamente as conexões da LAN para a trans- ferência dos pacotes de dados',
      peso: 4,
      imagemPergunta: 'https://www.electronics-tutorials.ws/wp-content/uploads/2022/08/binary-numbers.jpg',
    ),
    Pergunta(
      texto: 'O serviço que tem por objetivo realizar a “tradução” do endereço IP pelo domínio (nome) é conhecido por:',
      respostas: ['Ping', 'IP', 'DNS', 'VPN'],
      respostaCorreta: 'DNS',
      peso: 2,
      imagemPergunta: 'https://www.electronics-tutorials.ws/wp-content/uploads/2022/08/binary-numbers.jpg',
    ),
    Pergunta(
      texto: 'Considerando o modelo de arquitetura MVC, assinale a afirmação verdadeira.',
      respostas: ['O padrão MVC é apenas aplicável a linguagens orientadas ao desenvolvimento web como PHP.', 'O componente View é responsável pela interação com o usuário, exibindo dados.', 'O componente Controller é responsável pela leitura, escrita e validação de dados', 'O uso de MVC torna o processo de modelagem mais rápido, porém dificulta o reaproveitamento de código.'],
      respostaCorreta: 'O componente View é responsável pela interação com o usuário, exibindo dados.',
      peso: 3,
      imagemPergunta: 'https://digitalland.com.br/wp-content/uploads/2017/07/conheca-5-ferramentas-para-gestao-de-projetos-e-equipe-923x720.jpeg',
    ),
    Pergunta(
      texto: 'O Teste Estrutural de Caixa-Branca é uma abordagem para projetar casos de teste na qual os testes dependem do conhecimento da estrutura e da implementação do software. Essa abordagem também é conhecida como:',
      respostas: ['Teste Estrutural de software', 'Teste De Desempenho', 'Teste de Interface', 'Teste de Implementação'],
      respostaCorreta: 'Teste Estrutural de software',
      peso: 3,
      imagemPergunta: 'https://digitalland.com.br/wp-content/uploads/2017/07/conheca-5-ferramentas-para-gestao-de-projetos-e-equipe-923x720.jpeg',
    ),
    Pergunta(
      texto: 'Qual das alternativas NÃO representa um diagrama comportamental UML',
      respostas: ['Diagrama de Casos de Uso', 'Diagrama de Atividades', 'Diagrama de Sequência', 'Diagrama de Componentes'],
      respostaCorreta: 'Diagrama de Componentes',
      peso: 3,
      imagemPergunta: 'https://www.uml.org/images/UML-logo-346x332.png',
    ),
    Pergunta(
      texto: 'Qual o tipo de diagrama UML representado na imagem?',
      respostas: ['Casos de Uso', 'Pacotes', 'Objetos', 'Sequência'],
      respostaCorreta: 'Casos de Uso',
      peso: 4,
      imagemPergunta: 'https://d3n817fwly711g.cloudfront.net/uploads/2012/02/Use-Case-Diagram.jpg',
    ),
    Pergunta(
      texto: 'Qual o tipo de diagrama UML representado na imagem?',
      respostas: ['Classes', 'Estado de Maquina', 'Atividades', 'Implantação'],
      respostaCorreta: 'Atividades',
      peso: 4,
      imagemPergunta: 'https://d3n817fwly711g.cloudfront.net/uploads/2012/02/Activity-Diagram.jpg',
    ),
    Pergunta(
      texto: 'Componente que mantem o comutador funcionando mesmo com uma queda de energia',
      respostas: ['alimentador', 'fonte', 'nobreak', 'estabilizador'],
      respostaCorreta: 'nobreak',
      peso: 2,
      imagemPergunta: 'https://upload.wikimedia.org/wikipedia/commons/thumb/d/d5/Nvidia_gf4mx440_se.jpg/800px-Nvidia_gf4mx440_se.jpg',
    ),
    Pergunta(
      texto: 'Para que uma CPU possa executar um programa, ela busca instruçôes...',
      respostas: ['Na memória', 'No disco rigido', 'Na placa mãe', 'No processador'],
      respostaCorreta: 'Na memória',
      peso: 3,
      imagemPergunta: 'https://upload.wikimedia.org/wikipedia/commons/thumb/d/d5/Nvidia_gf4mx440_se.jpg/800px-Nvidia_gf4mx440_se.jpg',
    ),
    Pergunta(
      texto: 'Das seguintes opções qual delas NÃO representa um tipo de manutenção de software',
      respostas: ['Adaptativa', 'Evolutiva', 'Preservativa', 'Corretiva'],
      respostaCorreta: 'Preservativa',
      peso: 3,
      imagemPergunta: 'https://www.electronics-tutorials.ws/wp-content/uploads/2022/08/binary-numbers.jpg',
    ),
    Pergunta(
      texto: 'O principil de qualidade de software relacionado ao tempo de resposta e processamento e conhecido como',
      respostas: ['Praticidade', 'Velocidade', 'Eficiência', 'Resposta'],
      respostaCorreta: 'Eficiência',
      peso: 3,
      imagemPergunta: 'https://www.electronics-tutorials.ws/wp-content/uploads/2022/08/binary-numbers.jpg',
    ),
    Pergunta(
      texto: 'Qual dos sistemas operacionais a seguir NÃO e multitarefa com preempção',
      respostas: ['Windows 98', 'MS-DOS', 'OpenBSD', 'Linux'],
      respostaCorreta: 'MS-DOS',
      peso: 4,
      imagemPergunta: 'https://upload.wikimedia.org/wikipedia/commons/thumb/7/78/Appleterminal2.png/800px-Appleterminal2.png',
    ),
    
  ];